[modules]
left = ["Workspaces"]
center = ["WindowTitle"]
right = [
  "SystemInfo",
  [
    "Tray",
    "MediaPlayer",
    "Clock",
    "Privacy",
    "Settings",
  ],
  [
    "CustomNotifications",
  ],
]

[workspaces]
visibility_mode = "MonitorSpecific"
enable_workspace_filling = false

[clock]
format = "%a %d %b, %H:%M:%S"

[system_info]
indicators = ["Cpu", "Memory", "Temperature", "IpAddress"]

[system_info.cpu]
warn_threshold = 60
alert_threshold = 80

[system_info.memory]
warn_threshold = 70
alert_threshold = 85

[system_info.disk]
warn_threshold = 80
alert_threshold = 90

[[CustomModule]]
name = "CustomNotifications"
icon = ""
command = "swaync-client -t -sw"
listen_cmd = "swaync-client -swb"
icons.'dnd.*' = ""
alert = ".*notification"

[appearance]
style = "Islands"
scale_factor = 1.1

success_color = "#a6e3a1"
text_color = "#cdd6f4"

workspace_colors = ["#fab387", "#b4befe", "#cba6f7"]

[appearance.primary_color]
base = "#fab387"
text = "#1e1e2e"

[appearance.danger_color]
base = "#f38ba8"
weak = "#f9e2af"

[appearance.background_color]
base = "#1e1e2e"
weak = "#313244"
strong = "#45475a"

[appearance.secondary_color]
base = "#11111b"
strong = "#1b1b25"
